server:
  port: 8761
spring:
  application:
    name: naming-server
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true